import torch
import torch.autograd as autograd
import torch.nn.functional as f
import torch.optim as optim
torch.manual_seed(1)


In [3]:
import torch
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size,z.size())

torch.Size([4, 4]) <built-in method size of Tensor object at 0x000001FE406640D8> torch.Size([2, 8])


In [56]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

## creating tensors

In [4]:
x

tensor([[-1.4940,  0.5520,  1.4930, -0.6246],
        [-1.7791, -1.7367, -0.2297, -0.1898],
        [ 0.5040, -0.2125, -0.8612, -0.1065],
        [ 0.6851,  0.1432, -1.0554, -0.9026]])

In [5]:
T=[1.,2.,3.]

In [6]:
x=torch.randn(1)

In [7]:
x

tensor([0.9238])

## convert numpy array in torch tensor

In [8]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Automatic Differentiation

In [9]:
x=torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [11]:
y=x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [12]:
print(y.grad_fn)
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [13]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [18]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [19]:
out.backward()

In [20]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [22]:
x=torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y=y*2
    
    
print(y)    

tensor([  23.4241, -726.3685,  920.3095], grad_fn=<MulBackward0>)


In [27]:
#v=torch.tensor([0.1,1.0,0.0001])
#y.backward(v)
#print(x.grad)

## neural Networks in pytorch

In [29]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [49]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        
        self.conv1=nn.Conv2d(1,6,3)
        self.conv2=nn.Conv2d(6,16,3)
        
        self.fc1=nn.Linear(16*6*6,120)
        self.fc2=nn.Linear(120,84)
        self.fc3=nn.Linear(84,10)
    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x   
    def num_flat_features(self, x):
        size = x.size()[1:]  
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
net = Net()
print(net)      

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [50]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


## Loss function 

In [ ]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

## back propagate

In [ ]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)